# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wrok < Formula
  desc "A powerful command-line tool that combines lightweight todo management with time tracking"
  homepage "https://github.com/balkashynov/wrok"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/balkashynov/wrok/releases/download/v0.1.6/wrok_Darwin_x86_64.tar.gz"
      sha256 "69396d2428218823f787d18901af8ce145e6b1f5db2c92bb298e0222062f7696"

      def install
        bin.install "wrok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/balkashynov/wrok/releases/download/v0.1.6/wrok_Darwin_arm64.tar.gz"
      sha256 "3c74ed635135c918e76a817caaf33b67178f26dd398287a056782b3063bfd7fc"

      def install
        bin.install "wrok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/balkashynov/wrok/releases/download/v0.1.6/wrok_Linux_x86_64.tar.gz"
      sha256 "304f0d5f655395fa3e2433814feebebc83e44a5ee6a6aaea53d795d2454f0cb4"
      def install
        bin.install "wrok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/balkashynov/wrok/releases/download/v0.1.6/wrok_Linux_arm64.tar.gz"
      sha256 "62836f0af1ea6c7a65c535eab9b6135c65bd85a08160eb4e4b67596dd248107e"
      def install
        bin.install "wrok"
      end
    end
  end

  test do
    system "#{bin}/wrok --version"
  end
end
