# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wrok < Formula
  desc "A powerful command-line tool that combines lightweight todo management with time tracking"
  homepage "https://github.com/balkashynov/wrok"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/balkashynov/wrok/releases/download/v0.1.7/wrok_Darwin_x86_64.tar.gz"
      sha256 "0efeec473ff609ca07788bbaee20eb490d8d7e8614b7549b18d6e9b57e14a774"

      def install
        bin.install "wrok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/balkashynov/wrok/releases/download/v0.1.7/wrok_Darwin_arm64.tar.gz"
      sha256 "e62ab20884ceaefb5a6989a40de08a0a3e63537644ee34a93011e4edc1990f0c"

      def install
        bin.install "wrok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/balkashynov/wrok/releases/download/v0.1.7/wrok_Linux_x86_64.tar.gz"
      sha256 "cc8a0f137668c5f2b22c564fd68fcca69812b7bbb66256f44bfd5fc628eedf2d"
      def install
        bin.install "wrok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/balkashynov/wrok/releases/download/v0.1.7/wrok_Linux_arm64.tar.gz"
      sha256 "4a9c259c9669461efd1a508dd1d0c3254f0c8a550ca5ecdbc903a014b44b1067"
      def install
        bin.install "wrok"
      end
    end
  end

  test do
    system "#{bin}/wrok --version"
  end
end
