# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wrok < Formula
  desc "A powerful command-line tool that combines lightweight todo management with time tracking"
  homepage "https://github.com/balkashynov/wrok"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/balkashynov/wrok/releases/download/v0.1.2/wrok_Darwin_x86_64.tar.gz"
      sha256 "492178697fb6a4e2dcbebd8c4671c944be1cba1e6ace7e7db41814819fa95665"

      def install
        bin.install "wrok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/balkashynov/wrok/releases/download/v0.1.2/wrok_Darwin_arm64.tar.gz"
      sha256 "b7931e7a45a7b05ee5eb906bd959093c877451f5fd8bef00f2059a148d85a2d9"

      def install
        bin.install "wrok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/balkashynov/wrok/releases/download/v0.1.2/wrok_Linux_x86_64.tar.gz"
      sha256 "f1b899ab31e0530630fc5b61295a88514942852be299091bc626f3c18f3c5d53"
      def install
        bin.install "wrok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/balkashynov/wrok/releases/download/v0.1.2/wrok_Linux_arm64.tar.gz"
      sha256 "0d281155154775c1140cd6a1e527ee229bfae950a83186313d5cd41f5ce68e73"
      def install
        bin.install "wrok"
      end
    end
  end

  test do
    system "#{bin}/wrok --version"
  end
end
